[package]
name = "aerodesk-sfu"
description = "Remote desktop SFU server (str0m-based)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
str0m = { workspace = true, features = ["aws-lc-rs"] }
rouille.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
systemstat.workspace = true
aerodesk-protocol.workspace = true
aerodesk-core = { path = "../aerodesk-core" }
socket2 = { version = "0.5", features = ["all"] }
ctrlc = "3"
rustls = { version = "0.23", features = ["aws_lc_rs"] }
rustls-pemfile = "0.2"
ipnet = "2"

[dev-dependencies]
str0m-netem = { path = "../../../str0m/crates/netem" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[[bin]]
name = "rec2mp4"
path = "src/rec2mp4.rs"
